apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: express-sample-app
  app.kubernetes.io/instance: express-sample-app-instance
  app.kubernetes.io/name: express-sample-app
images:
- name: '*'
  newName: quay.io/nibrass_haider_ibm/express-sample-app
  newTag: 5a439e963abda6c910a77b1293a080a084a35d95
